### ISSUE TITLE
Cannot use without [core.incubator] dependency in project.clj

### ISSUE THREAD

**Issue by daveliepmann** [clojure-clutch/clutch#86]
If my _project.clj_ has `[com.ashafa/clutch "0.4.0"]` but not `[org.clojure/core.incubator "0.1.3"]` then I cannot use clutch.

In the REPL:

```
user=> (use 'com.ashafa.clutch)
FileNotFoundException Could not locate clojure/core/incubator__init.class or clojure/core/incubator.clj on classpath:   clojure.lang.RT.load (RT.java:443)
```

I get similar errors in emacs/CIDER when trying to evaluate a namespace with `(:require [com.ashafa.clutch :as clutch])`. 

Adding the core.incubator dependency mentioned above to _project.clj_ fixes the issue, but I feel it should not be necessary.

**Comment by squest** [comment]
I'm using clutch "0.4.0" and cemerick.url "0.1.1", it seems that I still need core.incubator to make it work. Any idea why?

**Comment by daveliepmann** [comment]
@squest Running `lein deps :tree` from the command line in your project directory should tell you where core.incubator is coming from.

**Comment by cemerick** [comment]
@squest  This fix is only on master, not in any release yet.

**Comment by squest** [comment]
Ahh I see. Thanks for both of you @cemerick @daveliepmann .

**Comment by yeehaa123** [comment]
@cemerick Will this fix be included in a release at some point? Or is this project officially discontinued? Would be a shame, because I still think that couch and clojure are a great combination. Especially when you throw PouchDb and ClojureScript in the mix.

**Comment by cemerick** [comment]
I think that's more up to @sritchie than anyone else these days? I'm not in a position to cut releases here anymore…

**Comment by sritchie** [comment]
I'm actually out of the game as well. Sorry guys! @dpetrovics is still working on couch, in addition to rethinkdb. He may be able to help.
