### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by dnaeon** [clojure-clutch/clutch#91]
I was looking for a library to use for CouchDB and found Clutch, but looking at the project history the last commit is from 2014.

Is this project still maintained or should we consider it abandoned?

**Comment by cemerick** [comment]
I know people are using it. I wouldn't take a lack of activity to imply a lack of quality, if that's what you're trying to assess.

As for maintenance, I am personally not likely to work on clutch further. Others might?

**Comment by daveliepmann** [comment]
@cemerick I see your point about the lack of constant updates not equating a lack of quality. And of course I respect anyone's need to not do unpaid work.

But I think the concern here is valid, and centers around the likelihood of minimum maintenance: well-written PRs being merged, dependencies updated at least every...year? I think you'd agree that in the absence of that minimum that one should consider the library abandoned, and look into alternatives like forking. Perhaps if that's the case then a "level of maintenance" notice or call for new maintainers would be considerate. Would you mind if I put together a PR adding such a notice to the README?

**Comment by cemerick** [comment]
The last commit on this repo was _four years ago_, and the last issue was filed _three years ago_. Either:

1. People are using it without incident, in which case such a "maintenance" notice would raise undue alarm. Or,
2. People aren't using clutch at all, and there's really just no point.

(BTW Dave: that latest three-year-old issue was filed by you…and you said you were too pressed for time to put together a PR. #89 I don't say this to be mean or anything, but the irony is tangible. ᖍ(ツ)ᖌ)

Anyone can fork the library whereever they like. Or, if someone has a sizable set of work they want to contribute, then they can be granted commit.

**Comment by daveliepmann** [comment]
>Dave: that latest three-year-old issue was filed by you…and you said you were too pressed for time to put together a PR.

I specifically remember coming back to that issue a few months later, after my deadline had passed and I had oodles of free time for whatever I wished, and thinking to myself: considering the fact that there's so little activity and so many open issues and PRs, and that none of the team of maintainers has acknowledged my ticket in any way, should I spend the time to make a PR that 1) won't be merged and 2) might not even be read?
