### ISSUE TITLE
Can I write some docs?

### ISSUE THREAD

**Issue by ericclack** [clojure-clutch/clutch#92]
I've been using Clojure, CouchDB and Clutch in a few of my projects and would like to write a little bit of documentation to make getting started easier, e.g. documenting the get-view functions.

I could do this on the project wiki (it seems like this could easily be turned on), or submit some pull requests to this repo (adding Markdown files), is this something someone could then review and merge? 

I'll keep things short and simple :)
-Eric.

**Comment by ashafa** [comment]
sure ...i'm available to review and merge

**Comment by ericclack** [comment]
Progress on a Pull Request here: #93

**Comment by ericclack** [comment]
Many thanks for the merge.

**Comment by ashafa** [comment]
No thank you for writing this up
